---  
- name: containerd installation on workers
  hosts: all
  roles: containerd-install

        
    - name: Set SystemdCgroup to true in /etc/containerd/config.toml
      lineinfile:
        path: "/etc/containerd/config.toml"
        regexp: "^\\s*SystemdCgroup\\s*=\\s*false"
        line: "SystemdCgroup = true"
        
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Restart containerd service
      systemd:
        name: containerd
        state: restarted
        
 - name: Installing K8S (kubeadm,kubelet&kubectl)on all nodes:
   hosts: all
   roles: k8s-install
    