---
- name: Installing containerd on workers
  hosts: all
  roles:
    - containerd-install

- name: Set SystemdCgroup to true in /etc/containerd/config.toml
  hosts: all
  roles:
    - cgroup-configuration

- name: Installing K8S (kubeadm, kubelet, kubectl) on all nodes
  hosts: all
  roles:
    - k8s-install

