---
# tasks file for k8s-install
- name: Installing K8S (kubeadm,kubelet&kubectl)on all nodes:
  tasks:
    - name: Load kernel modules
      shell: modprobe br_netfilter overlay
      
    - name: Modify /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        regexp: '^#net.ipv4.ip_forward='
        line: 'net.ipv4.ip_forward=1'
        backup: yes
        
    - name: Run apt update
      apt:
        update_cache: yes 
        
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - conntrack
        update_cache: yes
        state: present

    - name: Remove existing content from resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: ".*"
        state: absent

    - name: Add 403 nameserver to resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 10.202.10.202"
        create: yes
     
    - name: Download Kubernetes GPG key
      get_url:
        url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
        dest: "/tmp/kubernetes-apt-keyring.gpg"

    - name: Install Kubernetes GPG key
      copy:
        src: "/tmp/kubernetes-apt-keyring.gpg"
        dest: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
        mode: "0644"
        remote_src: yes

    - name: Remove temporary GPG key file
      file:
        path: "/tmp/kubernetes-apt-keyring.gpg"
        state: absent

    - name: Add Kubernetes repository line
      lineinfile:
        path: "/etc/apt/sources.list.d/kubernetes.list"
        line: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
        create: yes    
        
    - name: Remove existing content from resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        state: absent

    - name: Add nameserver to resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 10.202.10.202"
        create: yes
        
    - name: Run apt update
      apt:
        update_cache: yes

    - name: Install kubeadm
      apt:
        name: kubeadm
        state: present
        
    - name: Run apt update
      apt:
        update_cache: yes
        
    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Hold kubelet, kubeadm, and kubectl
      command: apt-mark hold {{ item }}
      loop:
        - kubelet
        - kubeadm
        - kubectl

